---
# Task

# Setting up new system
- name: Set hostname
  hostname:
    name: "{{ arch_hostname }}"

- name: Create user
  user:
    state: present
    name: "{{ arch_user }}"
    password: "{{ (arch_user_pw) | password_hash('sha512') }}"
    shell: /bin/zsh
    home: /home/{{ arch_user }}
    groups: "{{ arch_groups }}"
    update_password: on_create

- name: Give wheel group sudo rights
  lineinfile:
    path: /etc/sudoers
    regexp: "^# %wheel ALL=(ALL:ALL) ALL"
    line: "%wheel ALL=(ALL:ALL) ALL"

- name: Create my dir structure
  file:
    path: "{{ item }}"
    owner: "{{ arch_user }}"
    group: "{{ arch_user }}"
    state: directory
  with_items:
    - /home/{{ arch_user }}/Git
    - /home/{{ arch_user }}/Documents/backups
    - /home/{{ arch_user }}/Documents/help
    - /home/{{ arch_user }}/Documents/pentesting
    - /home/{{ arch_user }}/Documents/iso

# Import dotfiles
- name: Git checkout dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ arch_user }}/Git/dotfiles"

- name: Copy configs
  copy:
    src: "/home/{{ arch_user }}/Git/dotfiles/{{ item }}"
    dest: "/home/{{ arch_user }}"
    remote_src: yes
  with_items:
    - .config
    - .local
    - .zshrc
    - .tmux.conf
    - .vimrc
