---
# Task

# Harden SSH config
- name: Backup SSH configuration
  copy:
    remote_src: yes
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.backup
    force: no

- name: Create authorizedkeys file
  file:
    path: "~/.ssh/authorized_keys"
    state: touch

- name: Copy pub SSH key to machine
  authorized_key:
    user: "{{ arch_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Edit SSH config
  replace:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - { regexp: '^#PermitEmptyPasswords no$', replace: 'PermitEmptyPasswords no' }
    - { regexp: '^PermitRootLogin yes$', replace: 'PermitRootLogin no' }
  notify:
    - Restart sshd