---
# Handlers
- name: Restart sshd
  become: true
  service:
    name: sshd
    state: restarted

- name: Restart sddm
  become: true
  service:
    name: sddm.service
    enabled: true
    state: restarted